apiVersion: v2
name: helloworld
description: A Helm chart for FastAPI Hello World microservice
type: application

# Chart version - increment when you make changes to the chart
version: 1.0.0

# Application version - the version of the app being deployed
appVersion: "1.0.0"

maintainers:
  - name: Carmit
    email: carmit@example.com

